<SCRIPT LANGUAGE="JavaScript">
<!--
var NumberOfWords = 28
var words = new BuildArray(NumberOfWords)

// Use the following variables to 
// define your random words:
words[1] = "Lucas"words[2] = "Elias"words[3] = "Oscar"words[4] = "William"words[5] = "Hugo"words[6] = "Alexander"words[7] = "Oliver"words[8] = "Viktor"words[9] = "Erik"words[10] = "Axel"words[11] = "Filip"words[12] = "Emil"words[13] = "Isak"words[14] = "Leo"words[15] = "Liam"words[16] = "Theo"words[17] = "Anton"words[18] = "Melvin"words[19] = "Albin"words[20] = "Gustav"words[21] = "Max"words[22] = "Ludvig"words[23] = "Arvid"words[24] = "Edvin"words[25] = "Vincent"words[26] = "Viggo"words[27] = "Alvin"words[28] = "Wilmer"words[29] = "Adam"words[30] = "Noah"words[31] = "Elliot"words[32] = "Simon"words[33] = "Jonathan"words[34] = "Kevin"words[35] = "Olle"words[36] = "Benjamin"words[37] = "Linus"words[38] = "Carl"words[39] = "Alfred"words[40] = "Rasmus"words[41] = "Gabriel"words[42] = "Charlie"words[43] = "Jacob"words[44] = "Theodor"words[45] = "Nils"words[46] = "Leon"words[47] = "Felix"words[48] = "Sebastian"words[49] = "Noel"words[50] = "Casper"words[51] = "Malte"words[52] = "Sixten"words[53] = "Ville"words[54] = "David"words[55] = "Melker"words[56] = "Joel"words[57] = "Hampus"words[58] = "Neo"words[59] = "Adrian"words[60] = "Samuel"words[61] = "Love"words[62] = "Milo"words[63] = "Josef"words[64] = "Jack"words[65] = "Mohammed"words[66] = "Wilhelm"words[67] = "Alex"words[68] = "Daniel"words[69] = "Tim"words[70] = "Valter"words[71] = "Sigge"words[72] = "Vilgot"words[73] = "Robin"words[74] = "Marcus"words[75] = "Vidar"words[76] = "August"words[77] = "Milton"words[78] = "Måns"words[79] = "Hannes"words[80] = "Maximilian"words[81] = "Loke"words[82] = "Harry"words[83] = "Elis"words[84] = "John"words[85] = "Aron"words[86] = "Hjalmar"words[87] = "Otto"words[88] = "Elton"words[89] = "Mio"words[90] = "Fabian"words[91] = "Eddie"words[92] = "Sam"words[93] = "Svante"words[94] = "Dante"words[95] = "Ali"words[96] = "Johannes"words[97] = "Mattias"words[98] = "Jesper"words[99] = "Dennis"words[100] = "Ruben"

function BuildArray(size){
    this.length = size
    for (var i = 1; i <= size; i++){
        this[i] = null}
    return this
}

function PickRandomWord(frm) {
     var rnd = Math.ceil(Math.random() * NumberOfWords)

    frm.WordBox.value = words[rnd]
}
//-->
</SCRIPT>
